buildVariable: true
buildStatic: true
sources:
  - Wavefont.designspace
familyName: Wavefont
axisOrder:
  - ROND
  - YELA
  - wght
stat:
  - name: Roundness
    tag: ROND
    values:
    - name: Default
      value: 100
      flags: 2
  - name: Vertical Element Alignment
    tag: YELA
    values:
    - name: Default
      value: 0
      flags: 2